# Generated by Django 6.0.3 on 2026-03-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeconfig',
            name='engine_env_path',
            field=models.CharField(default='../soca-engine/.env', max_length=500),
        ),
        migrations.AlterField(
            model_name='edgeconfig',
            name='mediamtx_yml_path',
            field=models.CharField(default='../soca-engine/MediaMTX/mediamtx.yml', max_length=500),
        ),
    ]
