# Generated by Django 6.0.3 on 2026-03-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_edgeconfig_engine_env_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='edgeconfig',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='alert_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='snapshot_message',
            field=models.TextField(blank=True, default='{in_roi_count} object(s) detected at {time}', help_text='Placeholders: {count}, {in_roi_count}, {time}, {camera_id}, {job_id}, {category}'),
        ),
    ]
