# Generated by Django 6.0.3 on 2026-03-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_edgeconfig_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='conf_threshold',
            field=models.FloatField(default=0.5),
        ),
    ]
