# Generated by Django 6.0.3 on 2026-03-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_edgeconfig_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='publish_redis',
            field=models.BooleanField(default=True),
        ),
    ]
