# Generated by Django 6.0.3 on 2026-03-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_enable_publish_redis_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='edgeconfig',
            name='engine_db_path',
            field=models.CharField(blank=True, default='', help_text="Absolute path to soca-engine's SQLite file, e.g. /opt/soca-engine/db.sqlite3", max_length=500),
        ),
        migrations.AddField(
            model_name='edgeconfig',
            name='snapshots_root',
            field=models.CharField(blank=True, default='', help_text='Absolute path to snapshots directory, e.g. /opt/soca-engine/snapshots', max_length=500),
        ),
    ]
