# Generated by Django 6.0.3 on 2026-03-22 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_edge_operations_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='redis_url',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='telegram_webhook_url',
        ),
    ]
