# Generated by Django 6.0.3 on 2026-03-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_redis_url_telegram_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeconfig',
            name='redis_stream',
            field=models.CharField(default='soca:detections', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='iou_threshold',
            field=models.FloatField(default=0.45),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Intrusion', max_length=100)),
                ('cls_operator', models.CharField(default='in', max_length=10)),
                ('cls_ids', models.JSONField(default=list)),
                ('processing', models.CharField(default='in_roi', max_length=20)),
                ('duration_op', models.CharField(default='immediate', max_length=15)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('cooldown_seconds', models.IntegerField(default=60)),
                ('cron_schedule', models.CharField(default='* * * * *', max_length=50)),
                ('message_template', models.TextField(blank=True, default='')),
                ('action_telegram', models.BooleanField(default=False)),
                ('action_redis', models.BooleanField(default=False)),
                ('action_snapshot', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='app.schedule')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
