# Generated by Django 6.0.3 on 2026-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_edgeconfig_redis_stream_schedule_iou_threshold_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='trigger',
            field=models.CharField(default='present', max_length=10),
        ),
    ]
