# Generated by Django 6.0.3 on 2026-03-22 22:53

from django.db import migrations, models


def set_existing_users_as_admin(apps, schema_editor):
    User = apps.get_model('app', 'User')
    User.objects.all().update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rule_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.RunPython(set_existing_users_as_admin, migrations.RunPython.noop),
    ]
