# Generated by Django 6.0.3 on 2026-03-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_role_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=200)),
                ('app_name', models.CharField(default='SOCA Dashboard', max_length=200)),
                ('company_logo', models.FileField(blank=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Site Config',
            },
        ),
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.CharField(choices=[('Intrusion', 'Intrusion'), ('PPE', 'PPE'), ('Detection', 'Detection')], default='Intrusion', max_length=100),
        ),
    ]
