# Generated by Django 6.0.3 on 2026-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo_height',
            field=models.PositiveIntegerField(default=40, help_text='Logo height in pixels'),
        ),
    ]
