# Generated by Django 6.0.3 on 2026-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_logo_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='count_threshold',
            field=models.IntegerField(default=0, help_text='Min count to trigger (0 = not used)'),
        ),
        migrations.AddField(
            model_name='rule',
            name='crossing_line',
            field=models.JSONField(default=list, help_text='[[x1,y1],[x2,y2]] normalized, for People Counting mode'),
        ),
        migrations.AddField(
            model_name='rule',
            name='direction',
            field=models.CharField(choices=[('any', 'Any'), ('left_to_right', 'Left → Right'), ('right_to_left', 'Right → Left'), ('top_to_bottom', 'Top → Bottom'), ('bottom_to_top', 'Bottom → Top')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='rule',
            name='mode',
            field=models.CharField(choices=[('detection', 'Detection'), ('people_count', 'People Counting'), ('crowd', 'Crowd Detection')], default='detection', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lpr_model_path',
            field=models.CharField(blank=True, default='', help_text='Optional YOLO plate detection model, e.g. yolo/plate_det.pt', max_length=200),
        ),
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.CharField(choices=[('Intrusion', 'Intrusion'), ('PPE', 'PPE'), ('Detection', 'Detection'), ('Crowd', 'Crowd'), ('Counting', 'Counting')], default='Intrusion', max_length=100),
        ),
    ]
