# Generated by Django 6.0.3 on 2026-03-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rule_count_threshold_rule_crossing_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='crossing_direction',
            field=models.CharField(choices=[('any', 'Any'), ('left_to_right', 'Left → Right'), ('right_to_left', 'Right → Left'), ('top_to_bottom', 'Top → Bottom'), ('bottom_to_top', 'Bottom → Top')], default='any', help_text='Default crossing direction used by People Counting rules', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roi_type',
            field=models.CharField(choices=[('POLYGON', 'Polygon'), ('RECT', 'Rectangle'), ('LINE', 'Crossing Line')], default='POLYGON', max_length=20),
        ),
    ]
