# Generated by Django 6.0.3 on 2026-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_schedule_crossing_direction_alter_schedule_roi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.CharField(choices=[('Intrusion', 'Intrusion'), ('PPE', 'PPE'), ('Detection', 'Detection'), ('Crowd', 'Crowd'), ('Counting', 'Counting'), ('LPR', 'LPR')], default='Intrusion', max_length=100),
        ),
    ]
