# Generated by Django 6.0.3 on 2026-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_add_lpr_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeconfig',
            name='publisher_type',
            field=models.CharField(choices=[('redis', 'Redis Stream'), ('pubsub', 'Google Pub/Sub')], default='redis', help_text='Transport for publishing detection events', max_length=10),
        ),
        migrations.AddField(
            model_name='edgeconfig',
            name='pubsub_project_id',
            field=models.CharField(blank=True, default='', help_text='Google Cloud project ID, e.g. my-gcp-project', max_length=200),
        ),
        migrations.AddField(
            model_name='edgeconfig',
            name='pubsub_topic',
            field=models.CharField(blank=True, default='soca-detections', help_text='Pub/Sub topic name (not full path), e.g. soca-detections', max_length=200),
        ),
    ]
