# Generated by Django 6.0.3 on 2026-03-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_split_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgeconfig',
            name='gcs_bucket',
            field=models.CharField(blank=True, default='', help_text='GCS bucket name, e.g. soca-snapshot-bucket', max_length=200),
        ),
        migrations.AlterField(
            model_name='edgeconfig',
            name='gcs_path_prefix',
            field=models.CharField(blank=True, default='', help_text='GCS path prefix for this edge, e.g. edge-bekasi', max_length=200),
        ),
    ]
